from main.models import *

p = GroupData(group_id=1, group_name='member')
p.save()
p = GroupData(group_id=2, group_name='Mayor')
p.save()
p = GroupData(group_id=3, group_name='clerk')
p.save()

p = UserData(user_name='jautry', user_full_name='John Autry', user_status='logged_in', group_id=GroupData.objects.get(group_id=1))
p.save()
p = UserData(user_name='mbarnes', user_full_name='Michael Barnes', user_status='logged_in', group_id=GroupData.objects.get(group_id=1))
p.save()
p = UserData(user_name='pcannon', user_full_name='Patrick Cannon', user_status='logged_in', group_id=GroupData.objects.get(group_id=1))
p.save()
p = UserData(user_name='wcooksey', user_full_name='Warren Cooksey', user_status='logged_in', group_id=GroupData.objects.get(group_id=1))
p.save()
p = UserData(user_name='adulin', user_full_name='Andy Dulin', user_status='logged_in', group_id=GroupData.objects.get(group_id=1))
p.save()
p = UserData(user_name='cfallon', user_full_name='Claire Fallon', user_status='logged_in', group_id=GroupData.objects.get(group_id=1))
p.save()
p = UserData(user_name='dhoward', user_full_name='David Howard', user_status='logged_in', group_id=GroupData.objects.get(group_id=1))
p.save()
p = UserData(user_name='pkinsey', user_full_name='Patsy Kinsey', user_status='logged_in', group_id=GroupData.objects.get(group_id=1))
p.save()
p = UserData(user_name='lmayfield', user_full_name='LaWana Mayfield', user_status='logged_in', group_id=GroupData.objects.get(group_id=1))
p.save()
p = UserData(user_name='jmitchell', user_full_name='James Mitchell', user_status='logged_in', group_id=GroupData.objects.get(group_id=1))
p.save()
p = UserData(user_name='bpickering', user_full_name='Beth Pickering', user_status='logged_in', group_id=GroupData.objects.get(group_id=1))
p.save()
p = UserData(user_name='afox', user_full_name='Anthony Fox', user_status='logged_in', group_id=GroupData.objects.get(group_id=2))
p.save()
p = UserData(user_name='alastname', user_full_name='Ashley Lastname', user_status='logged_in', group_id=GroupData.objects.get(group_id=3))
p.save()

p = MotionData(motion_id=1, motion_clerk_id=UserData.objects.get(user_id=13))
p.save()
